const loveQuotes = [
    "I love you more than words can wield the matter, Dearer than eye-sight, space, and liberty.",
    "If I know what love is, it is because of you.",
    "You are my heart, my life, my one and only thought.",
    "My love for you is a journey, starting at forever and ending at never.",
    "I have found the one whom my soul loves.",
    "To the world you may be one person, but to one person you are the world.",
    "I swear I couldn't love you more than I do right now, and yet I know I will tomorrow.",
    "You are the finest, loveliest, tenderest, and most beautiful person I have ever known.",
    "I love you not only for what you are, but for what I am when I am with you.",
    "In all the world, there is no heart for me like yours. In all the world, there is no love for you like mine.",
    "I firmly believe that we belong together.",
    "Your love is all I need to feel complete.",
    "I choose you. And I'll choose you over and over and over. Without pause, without a doubt, in a heartbeat. I'll keep choosing you.",
    "I saw that you were perfect, and so I loved you. Then I saw that you were not perfect and I loved you even more.",
    "You are my sun, my moon, and all my stars.",
    "If I had a flower for every time I thought of you, I could walk through my garden forever.",
    "You make me happy in a way no one else can.",
    "My love for you is past the mind, beyond my heart, and into my soul.",
    "I exist in two places, here and where you are.",
    "Every love story is beautiful, but ours is my favorite.",
    "I love you right up to the moon—and back.",
    "You are the best thing that’s ever been mine.",
    "When I look into your eyes, I know I have found the mirror of my soul.",
    "You have bewitched me, body and soul, and I love, I love, I love you.",
    "If you live to be a hundred, I want to live to be a hundred minus one day so I never have to live without you.",
    "I want to be with you until my last page.",
    "Because of you, I laugh a little harder, cry a little less, and smile a lot more.",
    "You are my today and all of my tomorrows.",
    "I love you for all that you are, all that you have been, and all that you will be.",
    "Whatever our souls are made of, yours and mine are the same.",
    "I fell in love with the way you touched me without using your hands.",
    "You are my paradise and I would happily get stranded on you for a lifetime.",
    "I love you - those three words have my life in them.",
    "You are the poem I never knew how to write and this life is the story I have always wanted to tell.",
    "Walking with your hands in mine and mine in yours, that's exactly where I want to be always.",
    "I wish I could turn back the clock. I'd find you sooner and love you longer.",
    "You are my blue crayon, the one I never have enough of, the one I use to color my sky.",
    "I love you, not mainly because of how you look, but because of who you are... inside.",
    "My love for you is a journey; starting at forever, and ending at never.",
    "You are the source of my joy, the center of my world and the whole of my heart.",
    "When I tell you I love you, I don't say it out of habit. I say it to remind you that you're the best thing that ever happened to me.",
    "You are the last thought in my mind before I drift off to sleep and the first thought when I wake up each morning.",
    "I need you like a heart needs a beat.",
    "I love you because the entire universe conspired to help me find you.",
    "Ideally, couples need three lives; one for him, one for her, and one for them together.",
    "Your love shines in my heart as the sun that shines upon the earth.",
    "Age does not protect you from love. But love, to some extent, protects you from age.",
    "Thinking of you keeps me awake. Dreaming of you keeps me asleep. Being with you keeps me alive.",
    "I love you with every beat of my heart.",
    "You are the winner and the sole owner of my heart.",
    "Your voice is my favorite sound.",
    "So, I love you because the entire universe conspired to help me find you.",
    "To love and be loved is to feel the sun from both sides.",
    "A hundred hearts would be too few to carry all my love for you.",
    "The best thing to hold onto in life is each other.",
    "You know you're in love when you can't fall asleep because reality is finally better than your dreams.",
    "Love is like the wind, you can't see it but you can feel it.",
    "You are my greatest adventure.",
    "Every day with you is a new adventure.",
    "I love you more than yesterday, but less than tomorrow.",
    "My heart is and always will be yours.",
    "You are the missing piece to my puzzle.",
    "Life is better with you by my side.",
    "I want to grow old with you.",
    "You are my favorite notification.",
    "My favorite place is inside your hug.",
    "You are the reason I look down at my phone and smile.",
    "I love you to infinity and beyond.",
    "You are the apple of my eye.",
    "I love you bunches and oats.",
    "You are my happily ever after.",
    "I love you a bushel and a peck.",
    "You are my sunshine on a rainy day.",
    "I love you more than coffee, but please don't make me prove it.",
    "You are the peanut butter to my jelly.",
    "I love you even when I'm hungry.",
    "You are my favorite distraction.",
    "I love you like a fat kid loves cake.",
    "You are the cheese to my macaroni.",
    "I love you more than pizza.",
    "You are my favorite human.",
    "I love you more than sleep.",
    "You are the best thing since sliced bread.",
    "I love you with all my butt. I would say heart, but my butt is bigger.",
    "You are my lobster.",
    "I love you more than Kanye loves Kanye.",
    "You are the sprinkles on my donut.",
    "I love you from my head tomatoes.",
    "You are my cup of tea.",
    "I love you like a nerd loves math.",
    "You are the icing on my cupcake.",
    "I love you more than wifi.",
    "You are my sweet potato.",
    "I love you s'more every day.",
    "You are my pumpkin pie.",
    "I love you berry much.",
    "You are one in a melon.",
    "I love you a latte.",
    "You are my better half.",
    "I love you to the moon and back.",
    "You are my everything.",
    "I love you completely.",
    "You are my soulmate.",
    "I love you endlessly.",
    "You are my forever.",
    "I love you always.",
    "You are my heart.",
    "I love you dearly.",
    "You are my life.",
    "I love you deeply.",
    "You are my world.",
    "I love you truly.",
    "You are my treasure.",
    "I love you madly.",
    "You are my joy.",
    "I love you passionately.",
    "You are my dream.",
    "I love you intensely.",
    "You are my love.",
    "I love you constantly.",
    "You are my angel.",
    "I love you immensely.",
    "You are my star.",
    "I love you infinitely.",
    "You are my gem.",
    "I love you eternally.",
    "You are my rock.",
    "I love you forever.",
    "You are my light.",
    "I love you more.",
    "You are my destiny.",
    "I love you most.",
    "You are my fate.",
    "I love you best.",
    "You are my hope.",
    "I love you lots.",
    "You are my faith.",
    "I love you tons.",
    "You are my bliss.",
    "I love you loads.",
    "You are my wish.",
    "I love you big.",
    "You are my gift.",
    "I love you so.",
    "You are my prize.",
    "I love you too.",
    "You are mine.",
    "I love you.",
    "Be mine.",
    "Love you.",
    "Only you.",
    "True love.",
    "Real love.",
    "Pure love.",
    "Deep love.",
    "Big love.",
    "Our love.",
    "My love.",
    "Your love.",
    "Sweet love.",
    "Best love.",
    "Good love.",
    "Fine love.",
    "Hot love.",
    "Dear love.",
    "Kind love.",
    "Rich love.",
    "Warm love.",
    "Soft love.",
    "Fast love.",
    "Free love.",
    "Wild love.",
    "Sole love.",
    "Soul love.",
    "Life love.",
    "Live love.",
    "Give love.",
    "Take love.",
    "Make love.",
    "Keep love.",
    "Hold love.",
    "Show love.",
    "Feel love.",
    "Know love.",
    "Grow love.",
    "Send love.",
    "Find love.",
    "Safe love.",
    "Sure love.",
    "Firm love.",
    "Full love.",
    "High love.",
    "New love.",
    "Old love.",
    "One love.",
    "Two love.",
    "All love.",
    "Any love.",
    "Why love.",
    "How love.",
    "Who love.",
    "What love.",
    "Where love.",
    "When love.",
    "Yes, love.",
    "No, love.",
    "Maybe love.",
    "Always love.",
    "Never love.",
    "Sometimes love.",
    "Forever love.",
    "Together love.",
    "Apart love.",
    "Near love.",
    "Far love.",
    "Here love.",
    "There love.",
    "Everywhere love.",
    "Now love.",
    "Then love.",
    "Later love.",
    "Sooner love.",
    "Better love.",
    "Worse love.",
    "Harder love.",
    "Easier love.",
    "Stronger love.",
    "Weaker love.",
    "Greater love.",
    "Lesser love.",
    "Higher love.",
    "Lower love.",
    "Deeper love.",
    "Shallower love.",
    "Wider love.",
    "Narrower love.",
    "Brighter love.",
    "Darker love.",
    "Lighter love.",
    "Heavier love.",
    "Faster love.",
    "Slower love.",
    "Closer love.",
    "Further love.",
    "Simpler love.",
    "Complex love.",
    "Happy love.",
    "Sad love.",
    "Angry love.",
    "Calm love.",
    "Peaceful love.",
    "Chaotic love.",
    "Crazy love.",
    "Sane love.",
    "Healthy love.",
    "Sick love.",
    "Beautiful love.",
    "Ugly love.",
    "Cute love.",
    "Pretty love.",
    "Nice love.",
    "Sweet heart.",
    "Honey bun.",
    "Sugar pie.",
    "Love bug.",
    "Cuddle bear.",
    "Snuggle bunny.",
    "Teddy bear.",
    "Baby doll.",
    "Angel face.",
    "Dream boat.",
    "Lover boy.",
    "Lover girl.",
    "Sweet cheeks.",
    "Hot stuff.",
    "Sexy thing.",
    "Cutie pie.",
    "Buttercup.",
    "Pumpkin.",
    "Muffin.",
    "Cookie.",
    "Cupcake.",
    "Peanut.",
    "Jellybean.",
    "Gumdrop.",
    "Lollipop.",
    "Marshmallow.",
    "Snowflake.",
    "Rainbow.",
    "Sunshine.",
    "Moonlight.",
    "Starlight.",
    "Dewdrop.",
    "Raindrop.",
    "Teardrop.",
    "Heartbeat.",
    "Soulmate.",
    "Best friend.",
    "Partner.",
    "Companion.",
    "Helpmeet.",
    "Helpmat.",
    "Better half.",
    "Other half.",
    "Twin flame.",
    "Kindred spirit.",
    "True north.",
    "Guiding star.",
    "Safe harbor.",
    "Anchor.",
    "Rock.",
    "Foundation.",
    "Pillar.",
    "Support.",
    "Strength.",
    "Courage.",
    "Wisdom.",
    "Truth.",
    "Faith.",
    "Hope.",
    "Charity.",
    "Grace.",
    "Mercy.",
    "Peace.",
    "Joy.",
    "Happiness.",
    "Delight.",
    "Pleasure.",
    "Satisfaction.",
    "Contentment.",
    "Fulfillment.",
    "Completion.",
    "Perfection.",
    "Excellence.",
    "Beauty.",
    "Glory.",
    "Honor.",
    "Respect.",
    "Adoration.",
    "Devotion.",
    "Dedication.",
    "Loyalty.",
    "Fidelity.",
    "Trust.",
    "Belief.",
    "Confidence.",
    "Reliance.",
    "Dependence.",
    "Need.",
    "Want.",
    "Desire.",
    "Passion.",
    "Lust.",
    "Craving.",
    "Longing.",
    "Yearning.",
    "Hunger.",
    "Thirst.",
    "Wish.",
    "Hope.",
    "Dream.",
    "Vision.",
    "Goal.",
    "Aim.",
    "Purpose.",
    "Meaning.",
    "Significance.",
    "Importance.",
    "Value.",
    "Worth.",
    "Merit.",
    "Virtue.",
    "Goodness.",
    "Kindness.",
    "Gentleness.",
    "Patience.",
    "Forgiveness.",
    "Understanding.",
    "Compassion.",
    "Empathy.",
    "Sympathy.",
    "Care.",
    "Concern.",
    "Interest.",
    "Attention.",
    "Affection.",
    "Warmth.",
    "Tenderness.",
    "Intimacy.",
    "Closeness.",
    "Nearness.",
    "Presence.",
    "Existence.",
    "Being.",
    "Living.",
    "Life.",
    "Breath.",
    "Air.",
    "Water.",
    "Food.",
    "Shelter.",
    "Home.",
    "Safety.",
    "Security.",
    "Protection.",
    "Defense.",
    "Guard.",
    "Shield.",
    "Cover.",
    "Warmth.",
    "Comfort.",
    "Rest.",
    "Sleep.",
    "Relaxation.",
    "Ease.",
    "Peace.",
    "Quiet.",
    "Silence.",
    "Stillness.",
    "Calm.",
    "Serenity.",
    "Tranquility.",
    "Harmony.",
    "Balance.",
    "Order.",
    "Structure.",
    "Stability.",
    "Constancy.",
    "Permanence.",
    "Eternity.",
    "Infinity.",
    "Forever.",
    "Always.",
    "Evermore.",
    "Dateless.",
    "Timeless.",
    "Endless.",
    "Ceaseless.",
    "Unending.",
    "Undying.",
    "Immortal.",
    "Infinite.",
    "Boundless.",
    "Limitless.",
    "Measureless.",
    "Vast.",
    "Deep.",
    "High.",
    "Wide.",
    "Broad.",
    "Long.",
    "Tall.",
    "Big.",
    "Huge.",
    "Great.",
    "Grand.",
    "Majestic.",
    "Noble.",
    "Royal.",
    "Kingly.",
    "Queenly.",
    "Princely.",
    "Divine.",
    "Holy.",
    "Sacred.",
    "Blessed.",
    "Sanctified.",
    "Hallowed.",
    "Revered.",
    "Venerated.",
    "Worshipped.",
    "Idolized.",
    "Adored.",
    "Cherished.",
    "Treasured.",
    "Prized.",
    "Valued.",
    "Esteemed.",
    "Respected.",
    "Honored.",
    "Loved."
];

function getQuoteOfDay() {
    const now = new Date();
    const start = new Date(now.getFullYear(), 0, 0);
    const diff = now - start;
    const oneDay = 1000 * 60 * 60 * 24;
    const day = Math.floor(diff / oneDay);

    // Check local storage for "Missed Days" logic or just show today's
    // User wants: "Send notification if he also not visited on any day"
    // This implies we should show missed quotes if they missed a day?
    // For now, let's stick to the simpler "Current Day Quote" to match the 365 count.
    // If text is needed for "missed", we can add a backlog feature later.

    return loveQuotes[day % loveQuotes.length];
}

function getDailyNotification() {
    const quote = getQuoteOfDay();

    // Check if we already showed a notification TODAY
    const todayStr = new Date().toDateString();
    const lastSeen = localStorage.getItem('last_seen_date');

    if (lastSeen !== todayStr) {
        // New day, show notification!

        // 1. Try Browser Notification
        if ("Notification" in window) {
            if (Notification.permission === "granted") {
                new Notification("Daily Love Note ❤️", {
                    body: quote,
                    icon: "https://img.icons8.com/color/48/heart-puzzle.png"
                });
            } else if (Notification.permission !== "denied") {
                Notification.requestPermission().then(permission => {
                    if (permission === "granted") {
                        new Notification("Daily Love Note ❤️", {
                            body: quote,
                            icon: "https://img.icons8.com/color/48/heart-puzzle.png"
                        });
                    }
                });
            }
        }

        // 2. Show In-App Modal (Always works)
        showModal("📅 Daily Quote:\n\n" + quote);

        // Save today as seen
        localStorage.setItem('last_seen_date', todayStr);
    }
}

// TEST FUNCTION: Call this to force a notification to appear now
function forceDailyNotification() {
    // Clear the memory so it thinks we haven't seen it today
    localStorage.removeItem('last_seen_date');
    // Run the check again
    getDailyNotification();
    alert("Memory cleared! Notification logic triggered.");
}
